### ISSUE TITLE
Home Fragment

### ISSUE THREAD

**Issue by AbhiramVAnand** [AbhiramVAnand/Thorak#1]
Create a home fragment
## Tasks
- [x] Create Home fragments
- [x] Make the view transparent 
- [x] Create Clock
- [x] Long press
- [x] Right and Left swipe functions
- [x] Up and Down swipe functions
